name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Decode EC2 private key
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY_BASE64 }}" | base64 --decode > my_decoded_private_key.pem
          chmod 600 my_decoded_private_key.pem
          echo "GITHUB_RUNNER_IP=$(curl -s https://ifconfig.me)" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: Add inbound rule to EC2 security group
        run: |
          SECURITY_GROUP_ID=$(aws ec2 describe-security-groups --filters "Name=group-id,Values=sg-0c8489a0dca02126b" --query 'SecurityGroups[].GroupId' --output text)
          aws ec2 authorize-security-group-ingress --group-id "$SECURITY_GROUP_ID" --protocol tcp --port 22 --cidr "$GITHUB_RUNNER_IP/32"
          aws ec2 authorize-security-group-ingress --group-id "$SECURITY_GROUP_ID" --protocol tcp --port 80 --cidr "$GITHUB_RUNNER_IP/32"
          echo "Waiting 2 minutes for the security group changes to take effect"
          sleep 120

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/queue-app:latest

      - name: Install AWS CLI
        run: sudo apt-get install -y awscli

      - name: Deploy to EC2 instance
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          INSTANCE_ID: ${{ secrets.INSTANCE_ID }}
        run: |
          set -x
          PRIVATE_KEY_FILE=my_decoded_private_key.pem
          USER=ec2-user
          REMOTE_DOCKER_HOST=$USER@$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query 'Reservations[].Instances[].PublicDnsName' --output text)

          # Create a tarball of the necessary files
          tar czvf deployment.tar.gz --exclude='*.tar.gz' --exclude='*.pem' *

          # Transfer the tarball instead of all files individually
          scp -v -i $PRIVATE_KEY_FILE -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null deployment.tar.gz $REMOTE_DOCKER_HOST:/tmp

          # Extract the tarball on the remote instance and perform deployment
          ssh -t -i $PRIVATE_KEY_FILE -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $REMOTE_DOCKER_HOST "tar xzvf /tmp/deployment.tar.gz -C /tmp && aws ecr get-login-password --region ca-central-1 | sudo docker login --username AWS --password-stdin 750267477682.dkr.ecr.ca-central-1.amazonaws.com && sudo docker pull 750267477682.dkr.ecr.ca-central-1.amazonaws.com/queue-app:latest && (sudo docker stop $(sudo docker ps -aq --filter 'expose=80') && sudo docker rm $(sudo docker ps -aq --filter 'expose=80') || true) && sudo docker run -d --name queue-app --restart always -p 80:5001 750267477682.dkr.ecr.ca-central-1.amazonaws.com/queue-app:latest"
